apiVersion: v1
kind: Service
metadata:
  name: meethare-reserve-adjust
  labels:
    app: meethare-reserve-adjust
    service: meethare-reserve-adjust
spec:
  ports:
    - port: 8080
  selector:
    app: meethare-reserve-adjust
