apiVersion: v1
kind: Service
metadata:
  name: meethare-db-svc-headless
  labels:
    app: meethare-db-svc-headless
spec:
  ports:
    - name: http
      port: 80
  clusterIP: None
  selector:
    app: meethare-db-sts
