apiVersion: apps/v1
kind: Deployment
metadata:
  name: meethare-user-manage
  labels:
    app: meethare-user-manage
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: meethare-user-manage
      version: v1
  template:
    metadata:
      labels:
        app: meethare-user-manage
        version: v1
    spec:
      serviceAccountName: meethare-user-manage
      containers:
        - image: tprogramer/meethare-user-manage:latest
          name: meethare-user-manage
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
