apiVersion: v1
kind: Service
metadata:
  name: meethare-user-manage
  labels:
    app: meethare-user-manage
    service: meethare-user-manage
spec:
  ports:
    - port: 8080
  selector:
    app: meethare-user-manage
