apiVersion: apps/v1
kind: Deployment
metadata:
  name: meethare-location-recommend
  labels:
    app: meethare-location-recommend
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: meethare-location-recommend
      version: v1
  template:
    metadata:
      labels:
        app: meethare-location-recommend
        version: v1
    spec:
      serviceAccountName: meethare-location-recommend
      containers:
        - image: tprogramer/meethare-location-recommend:latest
          name: meethare-location-recommend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
