---
apiVersion: v1
kind: Secret
metadata:
  name: gitreposshkey
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:Yeoksam-Station-Exit-1/MeetHare-Infra.git
  sshPrivateKey: ${DEPLOY_KEY}
  insecure: "false"
  enableLfs: "true"
