server:
  extraArgs:
    - --insecure
  additionalApplications:
    - name: app-of-app
      namespace: argocd
      project: default
      source:
        repoURL: git@github.com:Yeoksam-Station-Exit-1/MeetHare-Infra.git
        targetRevision: HEAD
        path: argocd/services
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        #   allowEmpty: false
        syncOptions:
          # - Validate=true
          - CreateNamespace=true
          # - PrunePropagationPolicy=foreground
          # - PruneLast=true
