kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: argocd-server
  namespace: istio-system
spec:
  gateways:
    - argocd-server
  hosts:
    - "meethare.kro.kr"
    - "cluster.meethare.site"
  http:
    - match:
        - uri:
            prefix: /place
      route:
        - destination:
            host: meethare-place-recommend.default.svc.cluster.local
            port:
              number: 8080

    - match:
        - uri:
            prefix: /map
        - uri:
            prefix: /ws
      route:
        - destination:
            host: meethare-location-recommend.default.svc.cluster.local
            port:
              number: 8080

    - match:
        - uri:
            prefix: /user-manage
        - uri:
            prefix: /oauth2
        - uri:
            prefix: /login
      route:
        - destination:
            host: meethare-user-manage.default.svc.cluster.local
            port:
              number: 8080

    - match:
        - uri:
            prefix: /reserve
        - uri:
            prefix: /webpush
      route:
        - destination:
            host: meethare-reserve-adjust.default.svc.cluster.local
            port:
              number: 8080

    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
