kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: argocd-server
  namespace: istio-system
spec:
  gateways:
    - argocd-server
  hosts:
    - "meethare.site"
  http:
    - route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
      # - route:
      #     - destination:
      #         port:
      #           number: 8000
      #         host: httpbin
      #   match:
      #     - uri:
      #         prefix: /status
      #     - uri:
      #         prefix: /delay
