apiVersion: apps/v1
kind: Deployment
metadata:
  name: meethare-place-recommend
  labels:
    app: meethare-place-recommend
    version: v1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: meethare-place-recommend
      version: v1
  template:
    metadata:
      labels:
        app: meethare-place-recommend
        version: v1
    spec:
      serviceAccountName: meethare-place-recommend
      containers:
        - image: tprogramer/meethare-place-recommend:1.1.7
          name: meethare-place-recommend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
