apiVersion: v1
kind: Service
metadata:
  name: meethare-place-recommend
  labels:
    app: meethare-place-recommend
    service: meethare-place-recommend
spec:
  ports:
    - port: 8080
  selector:
    app: meethare-place-recommend
