apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: istio-system # 설정하지 않으면 `Issuing certificate as Secret does not exist` 에러 발생
type: Opaque
data:
  api-token: ${CLOUDFLARE_API_TOKEN}
