apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server
  namespace: istio-system
spec:
  secretName: argo-server-tls
  isCA: false
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cluster.meethare.site
  dnsNames:
    - cluster.meethare.site
