apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server
  namespace: istio-system
spec:
  secretName: argo-server-tls
  isCA: true
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: meethare.site
  dnsNames:
    - meethare.site
