# Prod

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: a41343095@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: istio
      # - dns01:
      #     cloudflare:
      #       email: a41343095@gmail.com
      #       apiTokenSecretRef:
      #         name: cloudflare-api-token-secret
      #         key: api-token
---
# Staging

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod2
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: a41343095@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod2
    solvers:
      - dns01:
          cloudflare:
            email: a41343095@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
