name: push to ssafy gitlab repo

on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 현재 브랜치 정보를 재활용하기 위한 작업
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      # 상위 폴더에서 미러링하고자 하는 GitLab Repo 클론하기
      - run: cd .. && git clone https://a41343095:$GITLAB_ACCESS_TOKEN@lab.ssafy.com/s09-final/S09P31A702.git
        env:
          # Repo Setting 클릭 -> Security: Secrets and variable: Actions 클릭 -> New Repository Secret 클릭한 후 등록
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}

      # GitLab 브랜치 전환
      - run: cd ../S09P31A702 && git switch ${{ steps.extract_branch.outputs.branch }} || git switch -c ${{ steps.extract_branch.outputs.branch }}

      # .git 폴더를 제외한 모든 작업물들을 GitLab에 복제로 덮어쓰기
      - run: mkdir -p ../S09P31A702/$REPO_NAME && \cp -Rf $(ls -a . | grep -Ev "^.git$|^.$|^..$") ../S09P31A702/$REPO_NAME
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      # 커밋하는 Author를 설정, 미설정 시 `Author identity unknown` 에러 발생
      - run: cd ../S09P31A702 && git config --global user.email "a41343095@gmail.com" && git config --global user.name "TProgramer"

      # 푸쉬한 커밋 메세지와 함께 현재 브랜치와 동일하게 GitLab에 push
      - run: cd ../S09P31A702 && git add . && git commit -m "${{ github.event.commits[0].message }}" && git push -u origin ${{ steps.extract_branch.outputs.branch }}
